### ISSUE TITLE
Feedback for “AI Agents”

### ISSUE THREAD

**Issue by auvtv** [Mintplex-Labs/anythingllm-docs#34]
is there an opption for using costume Agents? like a framework for developing an Agent and pluing it to AnythingLLM?

**Comment by timothycarambat** [comment]
In the UI we have a modal and text when typing in `@agent` that says custom agents are coming soon. So no, currently there is no custom agent support. We do plan on seeing if we can integrate tools like AutoGen and CrewAI so that you can resuse work you may have already done within the context of AnythingLLM
