### ISSUE TITLE
Feedback for “What is AnythingLLM”

### ISSUE THREAD

**Issue by JasonB1990** [Mintplex-Labs/anythingllm-docs#37]
Hey there, I just signed up and so far it looks impressive. 
A little confused though as it doesn't seem to be clear but I typically use a Vapi delivery framework for my Voice Agents and I like to use 11Labs for the voice model combined with Deepgram and Groq for extremely fast AI Agents. I was hoping that I could use Anything LLM to build and deploy these but everything seems to be just for local use. Which is fine for development but I also need to be able to deploy our ML and DL models for production at scale. 
Any guidance and docs that you can send me too as well as any docs you might have for the aforementioned AI Agents and embedding them or hosting them in the cloud for continous production delivery?

**Comment by timothycarambat** [comment]
AnythingLLM is not specifically designed to host or publish unauthenticated public chatbots or agents to the web. The docker version supports multi-user but this is more for "internal" team/collaborative use. We _do_ have the ability to take a workspace and [publish a chat widget to the web](https://docs.useanything.com/features/chat-widgets), but this is not the core focus of AnythingLLM.

Are you look for something more like Flowise? Where you chain together multiple tools, actions, and processes and get some kind of publishable chat widget/tool/expierence?

**Comment by JasonB1990** [comment]
No definitely not. That's just a no code solution and it doesn't support
Deepgram or Groq. I was misinformed when I became interested in your video.
I want to cancel the account and get a refund if possible. It's not usable
for me after exploring your cloud options.
I have included the account and receipt numbers.

**Comment by timothycarambat** [comment]
Then you need to email team@mintplexlabs.com - I do not have any emails in our inbox right now from anyone requesting a refund. If you respond to this specific email, it goes to Github and those details are probably stripped.

Provide me the email you used to sign up with to team@mintplexlabs.com and ill refund it. Github is not the place to request refunds since we can find your info that way @JasonB1990

**Comment by JasonB1990** [comment]
***@***.***

**Comment by timothycarambat** [comment]
@JasonB1990 again, you responded to this thread directly and Github will strip emails because this thread of comments is being posted publicly to Github https://github.com/Mintplex-Labs/anythingllm-docs/issues/37

**email team@mintplexlabs.com** in a new email, or else all i can see is  `***@***.***`

**Comment by JasonB1990** [comment]
Ok, thanks. Just sent it, my apologies. I am in the middle of projects and
didn't read the part about the email being stripped. My apologies. I sent
it to the email.

**Comment by JasonB1990** [comment]
And I'll keep you in mind. It would be a good solution for clients who want
a completely local LLM. So if I ever get a client who is looking for that
I'm sure I'll revisit this. So no hard feelings and no bridges burnt. In
fact, since we don't really compete with one another you might take a look
at my sites and take a look at what we do and we might share website
affiliate links or something on each others site and maybe recommend one
another. That might be a way where we could mutually help one another and
join forces so to speak.
www.babel-fish.ai and www.ai-jeannie.com   Let me know your thoughts on
that.
